#file: noinspection SpringBootApplicationYaml
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) [%clr(%X{correlation-id}){magenta}] %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

server:
  port: 8080

spring:
  datasource:
    mydb:
#      driver-class-name: com.mysql.jdbc.Driver
      name: personDb
      jdbcUrl: jdbc:mysql://localhost:3306/mydb
      username: user
      password: user
    test:
#      driver-class-name: ${spring.datasource.mydb.driver-class-name}
      name: courseDb
      jdbcUrl: jdbc:mysql://localhost:3306/test
      username: user
      password: user

